from __future__ import annotations

import csv as csv_module
import re
from datetime import datetime
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse
import xml.etree.ElementTree as ET


def _safe_filename(name: str) -> str:
    return re.sub(r"[^a-z0-9_\-]", "_", name.lower().strip())


def _add(parent, tag, attrs=None, text=None):
    elem = ET.SubElement(parent, tag, attrs or {})
    if text is not None:
        elem.text = str(text)
    return elem


def _prop(parent, ptype, name, value):
    return _add(parent, ptype, {"name": name}, str(value))


def _hash_tree(parent):
    return ET.SubElement(parent, "hashTree")


def _replace_tokens(text: str | None, replacements: list[tuple[str, str]]) -> str | None:
    if not text:
        return text
    out = text
    for old, new in replacements:
        if old and old in out:
            out = out.replace(old, new)
    return out


def _indent(elem, level=0):
    i = "\n" + level * "  "
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = i + "  "
        for child in elem:
            _indent(child, level + 1)
        if not elem[-1].tail or not elem[-1].tail.strip():
            elem[-1].tail = i
    if level and (not elem.tail or not elem.tail.strip()):
        elem.tail = i


def generate_jmx(
    app_name,
    transactions,
    correlations,
    csv_columns,
    user_journey_summary,
    output_path,
    num_threads=10,
    ramp_up=60,
    loop_count=1,
):
    all_reqs = [r for tx in transactions for r in tx.requests]
    default_scheme, default_host, default_port = _derive_base(all_reqs)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    replacements: list[tuple[str, str]] = []
    for c in correlations:
        if c.sample_value:
            sample = c.sample_value.replace("?", "")
            replacements.append((sample, f"${{{c.name}}}"))
    for col in csv_columns:
        if col.sample_values:
            replacements.append((col.sample_values[0], f"${{{col.column_name}}}"))

    root = ET.Element("jmeterTestPlan", {
        "version": "1.2",
        "properties": "5.0",
        "jmeter": "5.6.3",
    })
    root_ht = _hash_tree(root)

    test_plan = _add(root_ht, "TestPlan", {
        "guiclass": "TestPlanGui",
        "testclass": "TestPlan",
        "testname": f"{app_name} Performance Test",
        "enabled": "true",
    })
    _prop(test_plan, "stringProp", "TestPlan.comments", f"Generated by JMX Forge | {generated_at} | {user_journey_summary}")
    _prop(test_plan, "boolProp", "TestPlan.functional_mode", "false")
    _prop(test_plan, "boolProp", "TestPlan.serialize_threadgroups", "false")
    _prop(test_plan, "boolProp", "TestPlan.tearDown_on_shutdown", "true")
    udv = _add(test_plan, "elementProp", {
        "name": "TestPlan.user_defined_variables",
        "elementType": "Arguments",
        "guiclass": "ArgumentsPanel",
        "testclass": "Arguments",
        "testname": "User Defined Variables",
        "enabled": "true",
    })
    cprop = _add(udv, "collectionProp", {"name": "Arguments.arguments"})
    _write_udv(cprop, "PROTOCOL", default_scheme)
    _write_udv(cprop, "HOST", default_host)
    _write_udv(cprop, "PORT", str(default_port))
    for col in csv_columns:
        _write_udv(cprop, col.column_name, f"${{{col.column_name}}}")
    _prop(test_plan, "stringProp", "TestPlan.user_define_classpath", "")

    test_plan_ht = _hash_tree(root_ht)

    if csv_columns:
        csv_ds = _add(test_plan_ht, "CSVDataSet", {
            "guiclass": "TestBeanGUI",
            "testclass": "CSVDataSet",
            "testname": "CSV Test Data",
            "enabled": "true",
        })
        _prop(csv_ds, "stringProp", "filename", f"{_safe_filename(app_name)}_data.csv")
        _prop(csv_ds, "stringProp", "fileEncoding", "UTF-8")
        _prop(csv_ds, "stringProp", "variableNames", ",".join(c.column_name for c in csv_columns))
        _prop(csv_ds, "stringProp", "delimiter", ",")
        _prop(csv_ds, "boolProp", "ignoreFirstLine", "true")
        _prop(csv_ds, "boolProp", "quotedData", "false")
        _prop(csv_ds, "boolProp", "recycle", "true")
        _prop(csv_ds, "boolProp", "stopThread", "false")
        _prop(csv_ds, "stringProp", "shareMode", "shareMode.all")
        _hash_tree(test_plan_ht)

    defaults = _add(test_plan_ht, "ConfigTestElement", {
        "guiclass": "HttpDefaultsGui",
        "testclass": "ConfigTestElement",
        "testname": "HTTP Request Defaults",
        "enabled": "true",
    })
    _prop(defaults, "stringProp", "HTTPSampler.protocol", default_scheme)
    _prop(defaults, "stringProp", "HTTPSampler.domain", default_host)
    _prop(defaults, "stringProp", "HTTPSampler.port", str(default_port))
    args = _add(defaults, "elementProp", {
        "name": "HTTPsampler.Arguments",
        "elementType": "Arguments",
        "guiclass": "HTTPArgumentsPanel",
        "testclass": "Arguments",
        "testname": "User Defined Variables",
        "enabled": "true",
    })
    _add(args, "collectionProp", {"name": "Arguments.arguments"})
    _prop(defaults, "stringProp", "HTTPSampler.implementation", "HttpClient4")
    _hash_tree(test_plan_ht)

    cookies = _add(test_plan_ht, "CookieManager", {
        "guiclass": "CookiePanel",
        "testclass": "CookieManager",
        "testname": "HTTP Cookie Manager",
        "enabled": "true",
    })
    _add(cookies, "collectionProp", {"name": "CookieManager.cookies"})
    _prop(cookies, "boolProp", "CookieManager.clearEachIteration", "false")
    _hash_tree(test_plan_ht)

    thread_group = _add(test_plan_ht, "ThreadGroup", {
        "guiclass": "ThreadGroupGui",
        "testclass": "ThreadGroup",
        "testname": f"{app_name} Virtual Users",
        "enabled": "true",
    })
    _prop(thread_group, "stringProp", "ThreadGroup.on_sample_error", "continue")
    main = _add(thread_group, "elementProp", {
        "name": "ThreadGroup.main_controller",
        "elementType": "LoopController",
        "guiclass": "LoopControlPanel",
        "testclass": "LoopController",
        "testname": "Loop Controller",
        "enabled": "true",
    })
    _prop(main, "boolProp", "LoopController.continue_forever", "false")
    _prop(main, "intProp", "LoopController.loops", str(loop_count))
    _prop(thread_group, "stringProp", "ThreadGroup.num_threads", str(num_threads))
    _prop(thread_group, "stringProp", "ThreadGroup.ramp_time", str(ramp_up))
    _prop(thread_group, "boolProp", "ThreadGroup.scheduler", "false")

    tg_ht = _hash_tree(test_plan_ht)

    corr_map = {}
    for c in correlations:
        corr_map.setdefault(c.source_request_seq, []).append(c)

    for tx in transactions:
        tx_ctl = _add(tg_ht, "TransactionController", {
            "guiclass": "TransactionControllerGui",
            "testclass": "TransactionController",
            "testname": tx.name,
            "enabled": "true",
        })
        _prop(tx_ctl, "boolProp", "TransactionController.parent", "true")
        tx_ht = _hash_tree(tg_ht)

        for req in tx.requests:
            _write_sampler(tx_ht, req, replacements, corr_map.get(req.sequence, []))

        timer = _add(tx_ht, "ConstantTimer", {
            "guiclass": "ConstantTimerGui",
            "testclass": "ConstantTimer",
            "testname": "Think Time",
            "enabled": "true",
        })
        _prop(timer, "stringProp", "ConstantTimer.delay", str(tx.think_time))
        _hash_tree(tx_ht)

    tree = ET.ElementTree(root)
    _indent(root)
    tree.write(output_path, encoding="utf-8", xml_declaration=True)

    with open(output_path, "r", encoding="utf-8") as fh:
        return fh.read()


def _write_sampler(parent_hash_tree, req, replacements, extractors):
    parsed = urlparse(req.url)
    scheme = parsed.scheme or "https"
    host = parsed.hostname or "localhost"
    port = parsed.port or (443 if scheme == "https" else 80)

    query_pairs = parse_qsl(parsed.query or "", keep_blank_values=True)
    query_pairs = [(_replace_tokens(k, replacements) or "", _replace_tokens(v, replacements) or "") for k, v in query_pairs]
    query = urlencode(query_pairs)
    path = (parsed.path or "/") + (("?" + query) if query else "")

    sampler = _add(parent_hash_tree, "HTTPSamplerProxy", {
        "guiclass": "HttpTestSampleGui",
        "testclass": "HTTPSamplerProxy",
        "testname": f"{req.method.upper()} {(parsed.path or '/')[:60]}",
        "enabled": "true",
    })
    _prop(sampler, "stringProp", "HTTPSampler.domain", host)
    _prop(sampler, "stringProp", "HTTPSampler.port", str(port))
    _prop(sampler, "stringProp", "HTTPSampler.protocol", scheme)
    _prop(sampler, "stringProp", "HTTPSampler.path", path)
    _prop(sampler, "stringProp", "HTTPSampler.method", req.method.upper())
    _prop(sampler, "boolProp", "HTTPSampler.follow_redirects", "true")
    _prop(sampler, "boolProp", "HTTPSampler.auto_redirects", "false")
    _prop(sampler, "boolProp", "HTTPSampler.use_keepalive", "true")
    _prop(sampler, "boolProp", "HTTPSampler.DO_MULTIPART_POST", "false")

    body = _replace_tokens(req.body, replacements)
    args = _add(sampler, "elementProp", {
        "name": "HTTPsampler.Arguments",
        "elementType": "Arguments",
    })
    cprop = _add(args, "collectionProp", {"name": "Arguments.arguments"})
    if body:
        _prop(sampler, "boolProp", "HTTPSampler.postBodyRaw", "true")
        arg = _add(cprop, "elementProp", {"name": "", "elementType": "HTTPArgument"})
        _prop(arg, "boolProp", "HTTPArgument.always_encode", "false")
        _prop(arg, "stringProp", "Argument.value", body)
        _prop(arg, "stringProp", "Argument.metadata", "=")
    else:
        _prop(sampler, "boolProp", "HTTPSampler.postBodyRaw", "false")

    sampler_ht = _hash_tree(parent_hash_tree)

    hdrs = {k: _replace_tokens(v, replacements) for k, v in (req.headers or {}).items()}
    skip = {"host", "content-length", "connection", "accept-encoding", "cookie", ":authority", ":scheme", ":method", ":path"}
    hdrs = {k: v for k, v in hdrs.items() if k.lower() not in skip and v is not None}
    if hdrs:
        hm = _add(sampler_ht, "HeaderManager", {
            "guiclass": "HeaderPanel",
            "testclass": "HeaderManager",
            "testname": "HTTP Header Manager",
            "enabled": "true",
        })
        hprops = _add(hm, "collectionProp", {"name": "HeaderManager.headers"})
        for k, v in hdrs.items():
            h = _add(hprops, "elementProp", {"name": k, "elementType": "Header"})
            _prop(h, "stringProp", "Header.name", k)
            _prop(h, "stringProp", "Header.value", v)
        _hash_tree(sampler_ht)

    for corr in extractors:
        if corr.extractor_type == "json_path":
            ex = _add(sampler_ht, "JSONPostProcessor", {
                "guiclass": "JSONPostProcessorGui",
                "testclass": "JSONPostProcessor",
                "testname": f"Extract {corr.name}",
                "enabled": "true",
            })
            _prop(ex, "stringProp", "JSONPostProcessor.referenceNames", corr.name)
            _prop(ex, "stringProp", "JSONPostProcessor.jsonPathExprs", corr.extractor_expression)
            _prop(ex, "stringProp", "JSONPostProcessor.match_numbers", "1")
            _prop(ex, "stringProp", "JSONPostProcessor.defaultValues", f"NOT_FOUND_{corr.name}")
        else:
            ex = _add(sampler_ht, "RegexExtractor", {
                "guiclass": "RegexExtractorGui",
                "testclass": "RegexExtractor",
                "testname": f"Extract {corr.name}",
                "enabled": "true",
            })
            _prop(ex, "stringProp", "RegexExtractor.useHeaders", "true" if corr.source_location == "header" else "false")
            _prop(ex, "stringProp", "RegexExtractor.refname", corr.name)
            _prop(ex, "stringProp", "RegexExtractor.regex", corr.extractor_expression)
            _prop(ex, "stringProp", "RegexExtractor.template", "$1$")
            _prop(ex, "stringProp", "RegexExtractor.default", f"NOT_FOUND_{corr.name}")
            _prop(ex, "stringProp", "RegexExtractor.match_number", "1")
        _hash_tree(sampler_ht)


def _write_udv(parent_collection, name, value):
    arg = _add(parent_collection, "elementProp", {"name": name, "elementType": "Argument"})
    _prop(arg, "stringProp", "Argument.name", name)
    _prop(arg, "stringProp", "Argument.value", value)
    _prop(arg, "stringProp", "Argument.metadata", "=")


def _derive_base(requests):
    for r in requests:
        try:
            p = urlparse(r.url)
            if p.scheme and p.hostname:
                scheme = p.scheme
                host = p.hostname
                port = p.port or (443 if scheme == "https" else 80)
                return scheme, host, port
        except Exception:
            continue
    return "https", "localhost", 443


def generate_csv(csv_columns, output_path, num_rows=5):
    with open(output_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv_module.writer(fh)
        writer.writerow([col.column_name for col in csv_columns])
        for i in range(num_rows):
            row = []
            for col in csv_columns:
                base = col.sample_values[0] if col.sample_values else col.column_name
                row.append(base if i == 0 else f"{base}_{i + 1}")
            writer.writerow(row)
